<? foreach ($files as $file){?>
	<div>
		<input type="checkbox" class="deleteCssFiles" id='delete-<?= $file ?>'><span class="css-file" style="cursor:pointer;" id="selector-<?= $file ?>"><?= $file ?></span>
	</div>
<? } ?>
<!--<iframe id="fileBrowsers" src="editor/core/filebrowser/webFileBrowser.php" width="100%" style="height: 100%; margin: 0pt; top: 0pt; display: block; width: 100%; border: 0pt none; background: none repeat scroll 0% 0% rgb(168, 207, 238);"></iframe>-->
<!--<iframe id="fileBrowsers" name="fileBrowsers" frameborder="0" src="editor/core/AJAXBrowser/index.php" width="100%" style="height: 100%; margin: 0pt; top: 0pt; display: block; width: 100%; border: 0pt none; background: none repeat scroll 0% 0% rgb(168, 207, 238);"></iframe>-->
<? //include('filebrowser/webFileBrowser.php');  ?>

