<table cellpadding="0" cellspacing="0" border="0" style="border:0px solid #000000;" width="100%">
	<tr class="mainWindows" id="browseStyles" style="position:absolute;top:32px; left:0; z-index:1;width:100%;height:100%;background:#A8CFEE; border-right:1px solid #000000;">
		<td style="height:100%;">
			<? include('css-files.phtml'); ?>
		</td>
	</tr>
	<tr class="mainWindows" id="rawCss" style="position:absolute;top:32px; left:0; z-index:1;width:100%;height:100%;background:#A8CFEE; border-right:1px solid #000000;display:none;">
		<td style="height:100%;">
			<? include('rawCss.phtml'); ?>
		</td>
	</tr>
	<tr class="mainWindows" id="editStyles" style="height:100%;display:none;">
		<td valign="top" style="height:100%;width:20px;overflow-y:auto;background-color:#A8CFEE;">
			<? include('index.list.phtml'); ?>
		</td>
		<td width="20px">&nbsp;</td>
		<td valign="top">
			<? include('index.attributes.phtml'); ?>
		</td>
	</tr> 
	<tr class="mainWindows" id="inspectDom" style="display:none;position:absolute;top:42px; right:20px; z-index:-5000;width:800px;height:100%;background:#ffffff;border:1px solid #000000;">
		<td style="height:100%;">
			<textarea id="htmlDom" style="height:180px;"></textarea>
		</td>
	</tr>
</table>

<script type="text/javascript">
	$('#browseFiles').click(function(){
		$('.mainWindows').css('display', 'none');
		$('#browseStyles').css('display', 'block');
	});
	
	$('#editStyle').click(function(){
		$('.mainWindows').css('display', 'none');
		$('#editStyles').css('display', 'block');
	});
	
	$('#editRaw').click(function(){
		$('.mainWindows').css('display', 'none');
		$('#rawCss').css('display', 'block');
	});
	
	
</script>